import React from 'react';
import type { Metadata } from "next";
import { Monda } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./theme-provider";
// import Header from "@/components/Header";

const monda = Monda({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monda.className}>
        {/* <Header /> */}
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
